export const structuredDataBackedComponents = [
  "Breadcrumbs",
  "FAQPageBlock",
  "QAPageBlock",
  "HowToBlock",
  "TechArticleBlock",
  "SoftwareApplicationBlock",
  "SoftwareSourceCodeBlock",
  "FeatureGrid",
  "PackageGrid",
  "RelatedPackagesBlock",
  "RelatedApisBlock",
  "ProofMatrix",
  "ClaimReviewBlock",
  "CourseBlock",
  "LessonBlock",
  "CertificationPathBlock",
  "ComparisonMatrix",
  "DefinedTermSetBlock",
  "DatasetIndexBlock",
  "CodeExampleBlock",
  "ApiReferenceBlock",
  "WorkflowBlock",
  "LessonListBlock",
] as const;

export type StructuredDataBackedComponent = (typeof structuredDataBackedComponents)[number];
