import { LayoutDashboard, Globe, FileCode, CheckCircle2 } from 'lucide-react';
import MetadataViewer from '../components/MetadataViewer';

export default function MetadataHub() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-8">
      {/* Header */}
      <div className="border-b border-zinc-200 pb-5">
        <h1 className="font-sans text-3xl font-black tracking-tight text-zinc-950 flex items-center gap-2">
          <LayoutDashboard className="h-8 w-8 text-zinc-800" />
          Metadata & Discovery Hub
        </h1>
        <p className="mt-2 text-sm text-zinc-500 leading-relaxed max-w-3xl">
          Review the sitemap structures, search guidelines, structured JSON-LD graphs, and llms.txt summary specifications generated by the content pack to prove absolute search-engine and AI-agent discoverability.
        </p>
      </div>

      {/* Main Metadata Viewer widget */}
      <MetadataViewer />

      {/* Advisory stats Card */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
        <div className="rounded-xl border border-zinc-200 p-5 bg-zinc-50 space-y-1">
          <Globe className="h-5 w-5 text-zinc-700" />
          <h4 className="font-sans text-sm font-bold text-zinc-900 pt-1">
            SEO Indexability
          </h4>
          <p className="text-xs text-zinc-500 leading-relaxed">
            All routes have unique, stable titles, descriptions, and one canonical H1. The root robots.txt references multi-category sitemaps to maximize crawl paths.
          </p>
        </div>

        <div className="rounded-xl border border-zinc-200 p-5 bg-zinc-50 space-y-1">
          <CheckCircle2 className="h-5 w-5 text-zinc-700" />
          <h4 className="font-sans text-sm font-bold text-zinc-900 pt-1">
            AEO Direct Answers
          </h4>
          <p className="text-xs text-zinc-500 leading-relaxed">
            Every concept, package, command, and workflow page begins with a direct answer. Answer formats are optimized for fast NLP model extraction.
          </p>
        </div>

        <div className="rounded-xl border border-zinc-200 p-5 bg-zinc-50 space-y-1">
          <FileCode className="h-5 w-5 text-zinc-700" />
          <h4 className="font-sans text-sm font-bold text-zinc-900 pt-1">
            AiEO LLM Grounding
          </h4>
          <p className="text-xs text-zinc-500 leading-relaxed">
            Both robots.txt and sitemap trees reference llms.txt and semantic-index.json payloads, giving large language models instant, extractable facts.
          </p>
        </div>
      </div>
    </div>
  );
}
